// Generated by CoffeeScript 1.6.3
/* PACKAGES*/


(function() {
  var MONGO_URI, app, cc, db, express, mongo, port, yelp, _;

  express = require("express");

  mongo = require("mongodb");

  _ = require('underscore');

  app = express();

  MONGO_URI = process.env.MONGOLAB_URI || process.env.MONGOHQ_URL || "builder";

  db = require("mongojs").connect(MONGO_URI);

  yelp = require("yelp").createClient({
    consumer_key: "hq2hHKOYSQFmHU_wBOosyg",
    consumer_secret: "WvnfNhJ1Umcdcnyxo8xJ9QO5tGg",
    token: "YdrbgbIcPL1zwj1JI5SD3MHOfSHgkkV2",
    token_secret: "2UEu8pkO8G24vamnDwNTdKYdbpA"
  });

  cc = function(arguuments) {
    return _.each(arguments, function(arg) {
      return console.log(arg);
    });
  };

  port = process.env.PORT || 4040;

  app.listen(port, function() {
    return cc("listening on " + port);
  });

  /* CONFIGURATION*/


  app.configure(function() {
    app.use(express.logger("dev"));
    app.set("views", __dirname + "/views");
    app.set("view engine", "jade");
    app.use(express.errorHandler());
    app.locals.pretty = true;
    app.use(express.cookieParser());
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    return app.use(express["static"](__dirname + "/public"));
  });

  /* URI SCHEME*/


  app.get("/", function(req, res) {
    return res.render("index");
  });

  app.get("/search", function(req, res) {
    var requestobj;
    requestobj = {
      ll: req.query.lat + "," + req.query.lng,
      term: req.query.type
    };
    cc(requestobj);
    return yelp.search({
      location: 'Montreal',
      term: 'food'
    }, function(error, data) {
      if (typeof err === "undefined" || err === null) {
        cc(data.businesses.length);
        return res.json(data);
      } else {
        return res.json(err);
      }
    });
  });

}).call(this);
